INIT_NAME: "init_1"
DESCRIPTION: "imagenet"
DEBUG_MODE: true
CUDA:
  DEVICE:  0
  USEFLAG:  0
DATASET:
  NAME:  "webInterface"
  SET: []
  PROPOSAL:  "slidingwindow_v2"
  PARTFILTER:  ""
  QUERYSET:  "all"
  TARGETSET:  "all"
QUERIES:  "webInterface"
PATH:
  ROOT: ""
  FAISS:  ""
IMGTRAFO:
  MAX_SIZE:  224
  PADDING:  0
EXEMPLAR:
  FLAG:  false
  VERSION:  "cyvlfeat"
  PATCH_SIZE:  160
  ORIENTATIONS:  8
  PIXELS_PER_CELL:  16
  CELL_PER_BLOCK:  1
PY_FEATURE:
  CNN_MODEL: ''
  CNN_WEIGHTS_PATH: ''
  CNN_WEIGHTS: ''
  CHANNEL_DIM: 0
  STRIDE: 0
  NUM_SCALE: 1
  PADDING: 0
  WINDOW_SIZE: 5
  PCA_FLAG: false
  PCA_DIMENSION: 128
  PCA_MAX_FEATURE: 1000000
ROI_FEATURE:
  ROI_SIZE:
    - 5
    - 5
  WHITENING_FLAG:  false
  RANDOM_DROP_FLAG:  false
  NORMALIZE:  true
  PCA_FLAG:  true
  PCA_DIMENSION:  1024
  PCA_MAX_IMAGES:  500
  PCA_MAX_PATCHES:  100000
  RANDOM_DROP_FLAG: false
  RANDOM_DROP_DIMENSION:  1024
EXEMPLAR: 
  FLAG:  true
  NUM_NEGATIVES:  100
RETRAIN:
  NPOOL:
    FLAG: true
    NUM_NEGATIVES:  100
FAISS:
  INDEXTYPE:  'FlatIP'
